version: '3'
services:
# Ruby APP Setting
  app:
    container_name: ruby_docker
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./work_dir:/ruby_app
    stdin_open: true
    tty: true
